version: '3'
services:
  proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - sm_net

  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: school_management
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_net

  backend:
    image: backend:2.0
    build:
      context: school-manager-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      spring.jpa.show-sql: false
      spring.jpa.hibernate.ddl-auto: update
      server.servlet.context-path: /sm
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.username: root
      spring.datasource.password: password
      spring.datasource.url: jdbc:mysql://mysqldb:3306/school_management?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysqldb
    networks:
      - db_net
      - sm_net

  frontend:
    image: frontend:2.0
    build:
      context: ./school-manager-frontend
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    depends_on:
      - backend
    networks:
      - sm_net

networks:
  sm_net:
  db_net:

volumes:
  db_data: