GET {{urlBase}}/annees-scolaires

###
POST {{urlBase}}/annees-scolaires
Content-Type: application/json

{
  "annee": "2023",
  "dateDebut": "2023-10-02",
  "dateFin": "2024-06-12"
}


###
GET {{urlBase}}/annees-scolaires/1

