import './globals.css'
import {Box, Link as MuiLink, Typography} from "@mui/material";
import Link from "next/link";


export const metadata = {
    title: 'School Manager',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Box height={"100vh"} width={"100vw"} display={"flex"}>
            <Box height={"100%"} width={300} bgcolor={"red"}>
                <Link href={"/"}>
                    <Typography>{"Home"}</Typography>
                </Link>
            </Box>
            <Box>
                {children}
            </Box>
        </Box>
        </body>
        </html>
    )
}
