###
GET {{urlBase}}/classrooms
Accept: application/json

###
POST {{urlBase}}/classrooms
Content-Type: application/json

{
  "name": "9A",
  "level": "9eme Annee",
  "headTeacherName": "Mr. Smith",
  "schoolYear": {
    "id": 1
  }
}

###

